PUT http://localhost:3003/api/blogs/5f9982716546b53f1881cadd
Content-Type: application/json; charset=utf-8

{
    "title": "päivittetty blogi putilla",
    "author": "dddd",
    "url": "hthhth",
    "likes": 666
}